# Generated by Django 3.1.4 on 2021-02-22 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartFarm', '0006_auto_20210222_1448'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sensordata',
            table='SENSOR',
        ),
    ]
